
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Copy assets directory
        run: |
          mkdir -p github-pages-deploy-action-temp-deployment-folder/assets
          cp -r assets/* github-pages-deploy-action-temp-deployment-folder/assets/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder containing your index.html
          branch: gh-pages # The branch the action should deploy to
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
